/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iicTBSAQS4Y
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Loginpage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="border-b">
        <div className="container flex items-center justify-between h-14 px-4 sm:px-6 md:px-10">
          <nav className="hidden font-medium text-sm text-gray-500 sm:flex dark:text-gray-400">
          </nav>
          <nav className="flex items-center gap-4 text-sm font-medium dark:text-gray-400">
            <Link className="underline-off" href="/">
              Home
            </Link>
          </nav>
        </div>
      </header>
    <div className="flex items-center min-h-screen px-4 sm:px-6 lg:px-8">
      <div className="w-full max-w-[400px] mx-auto space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold">Mikee's Curtains</h1>
          <p className="text-gray-500 dark:text-gray-400">Welcome back!</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" />
          </div>
          <Button className="w-full">Login</Button>
        </div>
        <div className="space-y-2 text-center">
          <Link className="text-sm underline" href="#">
            Forgot your password?
          </Link>
          <p className="text-gray-500 dark:text-gray-400">
            Don't have an account?
            <Link className="underline" href="#">
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </div>
    </div>
  )
}
