/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JESZpaDCc2H
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function aboutcomp() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Features
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Pricing
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="grid gap-4">
        <section className="w-full py-12 md:py-24 lg:py-32 border-b">
          <div className="container grid items-center gap-4 px-4 md:px-6 lg:gap-10 lg:grid-cols-2">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter md:text-4xl/tight lg:text-5xl/tight">
                About Acme Inc
              </h1>
              <p className="text-gray-500 dark:text-gray-400">
                We're on a mission to help teams build the best frontend experiences. Our platform provides the tools
                and infrastructure to enable web development teams to innovate and ship faster.
              </p>
            </div>
            <div className="mx-auto flex items-center justify-center">
              <img
                alt="Image"
                className="aspect-[2/1] overflow-hidden rounded-lg object-cover object-center"
                height="200"
                src="/placeholder.svg"
                width="400"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight lg:text-5xl/tight">Our Mission</h2>
              <p className="max-w-[700px] text-gray-500 dark:text-gray-400">
                We believe that the web is the most important platform of our time. We're building the tools and
                infrastructure to enable web development teams to innovate and ship faster. Our platform provides the
                tools and infrastructure to enable web development teams to innovate and ship faster.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight lg:text-5xl/tight">Our History</h2>
              <p className="max-w-[700px] text-gray-500 dark:text-gray-400">
                Acme Inc was founded in 2019 by a team of experienced web developers who saw an opportunity to improve
                the way frontend teams build and deploy web applications. The company's first product was a CI/CD
                platform designed specifically for frontend developers.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight lg:text-5xl/tight">Meet the Team</h2>
              <p className="max-w-[700px] text-gray-500 dark:text-gray-400">
                Our team is made up of experienced web developers, designers, and product managers who are passionate
                about building the best frontend experiences. We are dedicated to helping our customers succeed by
                providing the tools and infrastructure they need to innovate and ship faster.
              </p>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="flex gap-4 items-start">
                <img
                  alt="Avatar"
                  className="rounded-lg w-20 overflow-hidden object-cover object-center"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">John Doe</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    John is an experienced web developer who has been working in the industry for over 10 years. He is
                    passionate about building fast and beautiful web experiences and is dedicated to helping our
                    customers succeed.
                  </p>
                </div>
              </div>
              <div className="flex gap-4 items-start">
                <img
                  alt="Avatar"
                  className="rounded-lg w-20 overflow-hidden object-cover object-center"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Jane Smith</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Jane is a frontend designer who is passionate about creating beautiful and intuitive user
                    interfaces. She has a keen eye for detail and is dedicated to ensuring that our platform provides
                    the best possible experience for our customers.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight lg:text-5xl/tight">Contact Us</h2>
              <p className="max-w-prose text-gray-500 dark:text-gray-400">
                Have a question or want to learn more about our platform? Contact our sales team at
                <Link className="underline" href="#">
                  sales@acme.com
                </Link>
              </p>
            </div>
            <div className="mx-auto max-w-[400px] space-y-4">
              <form className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" required />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="Enter your email" required type="email" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Enter your message" required />
                </div>
                <Button type="submit">Submit</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
