/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/s7ajDQb7mEA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import React from "react"

export function Cartsample() {
  return (
    <div className="border rounded-lg overflow-hidden">
      <table className="w-full table-auto">
        <thead className="bg-gray-100 dark:bg-gray-800">
          <tr>
            <th className="px-4 py-3 text-left font-medium">Name</th>
            <th className="px-4 py-3 text-right font-medium">Quantity</th>
            <th className="px-4 py-3 text-right font-medium">Price</th>
            <th className="px-4 py-3 text-right font-medium">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-200 dark:border-gray-700">
            <td className="px-4 py-3">
              <img
                alt="Product Image"
                className="rounded-md"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
            </td>
            <td className="px-4 py-3 font-medium">Cozy Blanket</td>
            <td className="px-4 py-3 text-right flex items-center justify-end gap-2">
              <Button className="h-8 w-8" size="icon" variant="outline">
                minus
                <span className="sr-only">Decrease quantity</span>
              </Button>
              <span>2</span>
              <Button className="h-8 w-8" size="icon" variant="outline">
                plus
                <span className="sr-only">Increase quantity</span>
              </Button>
            </td>
            <td className="px-4 py-3 text-right">$29.99</td>
            <td className="px-4 py-3 text-right">$59.98</td>
          </tr>
          <tr className="border-b border-gray-200 dark:border-gray-700">
            <td className="px-4 py-3">
              <img
                alt="Product Image"
                className="rounded-md"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
            </td>
            <td className="px-4 py-3 font-medium">Autumn Mug</td>
            <td className="px-4 py-3 text-right flex items-center justify-end gap-2">
              <Button className="h-8 w-8" size="icon" variant="outline">
                addminus
                <span className="sr-only">Decrease quantity</span>
              </Button>
              <span>1</span>
              <Button className="h-8 w-8" size="icon" variant="outline">
                add plus
                <span className="sr-only">Increase quantity</span>
              </Button>
            </td>
            <td className="px-4 py-3 text-right">$12.99</td>
            <td className="px-4 py-3 text-right">$12.99</td>
          </tr>
          <tr className="border-b border-gray-200 dark:border-gray-700">
            <td className="px-4 py-3">
              <img
                alt="Product Image"
                className="rounded-md"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
            </td>
            <td className="px-4 py-3 font-medium">Fall Fragrance Candle</td>
            <td className="px-4 py-3 text-right flex items-center justify-end gap-2">
              <Button className="h-8 w-8" size="icon" variant="outline">
                add minus icon here
                <span className="sr-only">Decrease quantity</span>
              </Button>
              <span>3</span>
              <Button className="h-8 w-8" size="icon" variant="outline">
                add pluss icon here
                <span className="sr-only">Increase quantity</span>
              </Button>
            </td>
            <td className="px-4 py-3 text-right">$16.99</td>
            <td className="px-4 py-3 text-right">$50.97</td>
          </tr>
        </tbody>
        <tfoot className="bg-gray-100 dark:bg-gray-800">
          <tr>
            <th className="px-4 py-3 text-right font-medium" colSpan={4}>
              Total:
            </th>
            <th className="px-4 py-3 text-right font-medium">$123.94</th>
          </tr>
        </tfoot>
      </table>
    </div>
  )
}
