/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VqZkKt7ikS8
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function index() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="border-b">
        <div className="container flex items-center justify-between h-14 px-4 sm:px-6 md:px-10">
          <nav className="hidden font-medium text-sm text-gray-500 sm:flex dark:text-gray-400">
            <Link className="underline-off" href="#">
              help@mikeescurtains.com
            </Link>
          </nav>
          <Link className="font-bold text-lg md:text-xl dark:text-gray-50" href="#">
            Mikee's Curtains
          </Link>
          <nav className="flex items-center gap-4 text-sm font-medium dark:text-gray-400">
            <Link className="underline-off" href="#">
              Home
            </Link>
            <Link className="underline-off" href="#">
              Curtains
            </Link>
            <Link className="underline-off" href="#">
              Contact
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Welcome to Mikee's Curtains
              </h1>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Beautifully designed curtains for your home. Custom sizes available. Free shipping on all orders.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex space-x-2">
                <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                <Button type="submit">Sign Up</Button>
              </form>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Sign up to get notified when we launch.
                <Link className="underline underline-offset-2" href="#">
                  Terms & Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Featured Products</h2>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-4 sm:grid-cols-2 md:gap-8 lg:max-w-5xl lg:grid-cols-3">
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2">
                <img
                  alt="Image"
                  className="aspect-square overflow-hidden rounded-md object-cover object-center"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
                <div className="space-y-2">
                  <h3 className="font-bold">Elegance Sheer Curtains</h3>
                  <p className="font-semibold">$49.99</p>
                </div>
                <Button size="sm">Add to Cart</Button>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Mikee's Curtains. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            About Us
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Contact
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms & Conditions
          </Link>
        </nav>
      </footer>
    </div>
  )
}
